### ISSUE TITLE
mb_substr() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by leonwisdom** [narendravaghela/cakephp-remember-me#2]
Hi, first of all let me start by thanking you for such an awesome plugin but i'm having an issue when logging out and then logging back in with a different user on my website, i get the error: mb_substr() expects parameter 1 to be string, array given. It seems like on logout $this->RememberMe->removeRememberedData(); is not fully clearing the cookie.

Any help would be greatly appreciated

**Comment by narendravaghela** [comment]
Hi,
As a first thing, please clear your browser cookies and try again. Also, could you please let me know which version of Cake you are using?

**Comment by narendravaghela** [comment]
@WisdomProductionz By the way, I have updated the component code and released a new version.
Please use the latest version and let me know if the problem still exists.

**Comment by narendravaghela** [comment]
@WisdomProductionz Does it work for you? If so, please let me know and I will close this issue.

**Comment by leonwisdom** [comment]
@narendravaghela thank you for the response, I'm using the latest version of Cakephp and clearing the browser cache sometimes works but on live site, users may have multiple accounts and may not know about clearing their browser cache to fix the issue before switching to a another account. I haven't had the chance to see if you're new release would fix the issue as I'm away untill Friday but soon as I get back I'll get back to you.

Thank you

**Comment by leonwisdom** [comment]
@narendravaghela i have tried the updated version and don't seem to be having the issues anymore, thank you for a quick swift fix

**Comment by narendravaghela** [comment]
Glad to hear that :) Have a nice weekend!
